### ISSUE TITLE
Other mouse clicks

### ISSUE THREAD

**Issue by kristian-puccio** [mjrusso/scoot#16]
Not sure if I haven't read the instructions properly yet but I couldn't see how to initiate a right click.
I guess it would be a little tricky as it would quite often bring up a context menu that may be hard to target.

Anyhow thanks for Scoot great idea!

**Comment by mjrusso** [comment]
You're not doing anything wrong -- support for right (and middle) clicking aren't actually implemented.

I quickly hacked together right click support last night, but (as you predicted) Scoot isn't able to interact with the context menu. (There are still other system shortcuts for selecting items in the menu, so that's good at least.) I want to try a few other things out before giving up, but I will add shortcuts for right and middle clicking regardless.

**Comment by mjrusso** [comment]
Check out #20, which dramatically improves clicking support. 

(Unfortunately, I couldn't find a way for Scoot to take control of the mouse cursor when a context menu is active.)

**Comment by kristian-puccio** [comment]
Legend!
I'll take a look thanks!

**Comment by mjrusso** [comment]
Now available in v0.9: https://github.com/mjrusso/scoot/releases/tag/v0.9

**Comment by kristian-puccio** [comment]
This is awesome! thanks works well.
The context menu is very easy to use using existing OSX keyboard nav 👍
